FROM registry.access.redhat.com/hi/go:1.27-builder as builder
ARG XK6_VERSION=v1.4.13
ARG K6_VERSION=v2.2.0
ARG REMOTE_WRITE_EXTENSION_VERSION=v0.5.3

RUN dnf install -y git
RUN mkdir -p /out && \
    go install go.k6.io/xk6@${XK6_VERSION} && \
    CGO_ENABLED=0 /go/bin/xk6 build \
      --with github.com/grafana/xk6-client-prometheus-remote@${REMOTE_WRITE_EXTENSION_VERSION} \
      --output /out/k6

FROM registry.access.redhat.com/hi/static:latest

COPY --from=builder /out/k6 /usr/local/bin/k6
COPY load.js /opt/rhobs-testing/load.js

ENV K6_NO_USAGE_REPORT=true

ENTRYPOINT ["/usr/local/bin/k6", "run", "/opt/rhobs-testing/load.js"]
